-- MySQL Script generated by MySQL Workbench
-- Fri Nov 14 22:26:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema brecho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema brecho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brecho` DEFAULT CHARACTER SET utf8 ;
USE `brecho` ;

-- -----------------------------------------------------
-- Table `brecho`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brecho`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `senha` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `brecho`.`roupas_tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brecho`.`roupas_tipos` (
  `idtipo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brecho`.`roupas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brecho`.`roupas` (
  `idroupas` INT NOT NULL AUTO_INCREMENT,
  `preco` DECIMAL(8,2) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `roupas_tipos_idtipo` INT NOT NULL,
  PRIMARY KEY (`idroupas`),
  INDEX `fk_roupas_roupas_tipos1_idx` (`roupas_tipos_idtipo` ASC),
  CONSTRAINT `fk_roupas_roupas_tipos1`
    FOREIGN KEY (`roupas_tipos_idtipo`)
    REFERENCES `brecho`.`roupas_tipos` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brecho`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brecho`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idclientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brecho`.`transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brecho`.`transacao` (
  `idtransacao` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `roupas_idroupas` INT NOT NULL,
  `clientes_idclientes` INT NOT NULL,
  PRIMARY KEY (`idtransacao`),
  INDEX `fk_transacao_roupas_idx` (`roupas_idroupas` ASC),
  INDEX `fk_transacao_clientes1_idx` (`clientes_idclientes` ASC),
  CONSTRAINT `fk_transacao_roupas`
    FOREIGN KEY (`roupas_idroupas`)
    REFERENCES `brecho`.`roupas` (`idroupas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacao_clientes1`
    FOREIGN KEY (`clientes_idclientes`)
    REFERENCES `brecho`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
